### ISSUE TITLE
Bump goth to ~> 1.0

### ISSUE THREAD

**Issue by wojtekmach** [plataformatec/broadway_cloud_pub_sub#21]
Since there's a stable release we should test against it and update code and docs accordingly.

**Comment by mcrumm** [comment]
Goth 1.x should work fine, but when we upgrade, we'll probably want to pin `poison <= 4.0` because of googleapis/elixir-google-api#1232

Otherwise I'm afraid we'll get a lot of issues around errors caused by version mismatches.

**Comment by wojtekmach** [comment]
Thanks for the heads-up! Looks like recent gax [has the following requirement on poison]:(https://github.com/googleapis/elixir-google-api/blob/6f322931914295031f87c244d019a8c00dea1029/clients/gax/mix.exs#L30)

```elixir
{:poison, ">= 1.0.0 and < 4.0.0"},
```

so we may already be good but I'll definitely double-check.

**Comment by mcrumm** [comment]
Oh, that's right.  They fixed the dependency, but not the compatibility with Poison v4, as of `0.1.3`.

**Comment by vans163** [comment]
Just pumped into this issue on latest goth 1.1.0, had to set poison under <4.0.0
